#!/bin/bash
set -eo pipefail

function log() {
  echo " ---> $1"
}

log "Updating all packages, installing editor"

yum upgrade -y
yum install -y vim

log "Installing dependencies"

yum install -y gcc wget make bzip2 automake gdbm-devel \
  libffi-devel libyaml-devel openssl-devel ncurses-devel \
  readline-devel zlib-devel 2> /dev/null

yum clean all

log "Setting up Ruby environment with ruby-install"

release_url="https://github.com/postmodern/ruby-install/archive/v0.4.3.tar.gz"

cd /usr/local/src
wget -O ruby-install-0.4.3.tar.gz $release_url
tar -xzf ruby-install-0.4.3.tar.gz
cd ruby-install-0.4.3
make install

ruby-install -i /usr/local/ ruby $DEFAULT_RUBY_VERSION 2> /dev/null

log "Ruby installation completed, adding extras"

yum install -y git perl-Digest 2> /dev/null
gem install bundler

exit 0
