- set_fact:
    consul_pkg_filename: "{{consul_version}}_linux_amd64.zip"
    consul_ui_pkg_filename: "{{consul_version}}_web_ui.zip"


- name: Downloading consul
  get_url:
    sha256sum: "{{consul_sha256sum}}"
    url: "https://dl.bintray.com/mitchellh/consul/{{consul_pkg_filename}}"
    dest: "{{temp_dir}}/{{consul_pkg_filename}}"

- name: Extracting consul binary
  shell: "cd {{temp_dir}} && unzip {{consul_pkg_filename}}"

- name: Moving consul binary
  shell: "mv {{temp_dir}}/consul {{pkg_dir}}/"



- name: Downloading consul UI
  when: install_consul_ui
  get_url:
    sha256sum: "{{consul_ui_sha256sum}}"
    url: "https://dl.bintray.com/mitchellh/consul/{{consul_ui_pkg_filename}}"
    dest: "{{temp_dir}}/{{consul_ui_pkg_filename}}"

- name: Extracting consul UI
  when: install_consul_ui
  shell: "cd {{temp_dir}} && unzip {{consul_ui_pkg_filename}}"

- name: Moving consul UI
  when: install_consul_ui
  shell: "mv {{temp_dir}}/dist {{pkg_dir}}/ui"