#!/bin/bash

echo
echo "Seaworthy installation completed. Performing post-install tasks:"
echo

if [[ ! -e "/etc/resolv.conf.orig" ]]; then
	echo "  - Saving copy of resolv.conf"
	cat /etc/resolv.conf > /etc/resolv.conf.orig
fi

echo "  - Creating local configuration directories/files"
mkdir -p /usr/local/cluster/consul
mkdir -p /usr/local/cluster/checks

mkdir -p /etc/cluster/consul



common_components=( consul nsqd nsqevents )
for component in "${common_components[@]}"; do
	echo "  - Enabling $component components"
	seactl component enable $component
done

echo "  - Linking docker.service overrides"
ln -s /usr/cluster/systemd/docker.service.d /etc/systemd/docker.service.d
