#!/bin/bash

echo "Starting admiral container"

docker run -i -t --rm --name admiral \
	-e SERF_ROUTABLE_IP=$SERF_ROUTABLE_IP \
	-e SERF_NODE_NAME=admiral \
	-e SERF_BIND_PORT=5000 \
	-e SERF_JOIN_NODE=$SERF_ROUTABLE_IP:5000 \
	-e SERF_ROLE=admiral \
	-p 5000:5000 \
	vlipco/deckhouse /srv/bin/start-serf