- name: "{{component}}: Loading installation variables"
  include_vars: generic/vars.yml

- name: "{{component}}: Removing previous folder"
  when: clean_install | default(False)
  file:
    path: "{{target_dir}}"
    state: absent

- name: "{{component}}: Creating component folders"
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - "{{target_dir}}"
    - "{{consul_conf_dir}}"

- name: "{{component}}: Running installer to verify version or install"
  with_fileglob: installer_glob
  script: "{{item}} {{package_target_dir}}"

- name: "{{component}}: Copying bin"
  with_fileglob: binaries_glob
  copy:
    mode: 0755
    src: "{{item}}"
    dest: "{{bin_dir}}/"

- name: "{{component}}: Copying consul checks"
  with_fileglob: consul_checks_glob
  copy:
    mode: 0755
    src: "{{item}}"
    dest: "{{checks_dir}}/"

- name: "{{component}}: Compiling consul templates"
  with_fileglob: consul_templates_glob
  template:
    src: "{{item}}"
    dest: "{{consul_conf_dir}}/"

- name: "{{component}}: Copying systemd units"
  with_fileglob: systemd_units_glob
  register: units_install
  copy:
    src: "{{item}}"
    dest: "{{systemd_dir}}/"

- name: "{{component}}: Linking component parts"
  script: "generic/link-cluster-component {{component}}"
  notify: check links

- name: "{{component}}: Notifying component's systemd handler"
  command: /bin/true
  with_fileglob: systemd_units_glob
  notify: "restart {{component}}"
