#!/bin/bash
set -eo pipefail

component="$1"
component_dir="/cluster/components/$component"
bin_dir="$component_dir/bin"
systemd_dir="$component_dir/systemd"
consul_conf_dir="$component_dir/consul"
event_handlers_dir="$component_dir/events"

function link_folder() {
	src="$1"
	dest="$2"
	if [[ -d "$src" ]]; then
		cd "$src"
		echo "Linking items in $src:"
		for file in $(ls . -1); do
			rm $dest/$file &> /dev/null || true
			echo "  $file -> $dest/$file"
			ln -s $src/$file $dest/$file
		done
	else
		echo "$src doesn't exist, skipping"
	fi
}

mkdir -p /cluster/etc/consul
mkdir -p /cluster/etc/events

link_folder $event_handlers_dir /cluster/etc/events
link_folder $consul_conf_dir /cluster/etc/consul
link_folder $bin_dir /usr/local/bin
link_folder $systemd_dir /etc/systemd/system
