- name: Installing common gems
  tags: common
  shell: "cd {{components_dir}}/common/misc && /usr/local/bin/bundle install"

- name: Creating script to prevent resolv.conf modifications
  copy:
    content: "function make_resolv_conf() { : }"
    dest: /etc/dhcp/dhclient-enter-hooks

- name: Setting script permissions
  file:
    mode: 0755
    path: /etc/dhcp/dhclient-enter-hooks

- name: Save DNS backup
  shell: >
    cp /etc/resolv.conf /etc/resolv.conf.orig
    creates=/etc/resolv.conf.orig

- name: Checking for NetworkManager.conf
  stat: path=/etc/NetworkManager/NetworkManager.conf
  register: network_manager_info

- name: Disable NetworkManager DNS management
  when: network_manager_info.stat.exists
  ini_file:
    backup: yes
    dest: /etc/NetworkManager/NetworkManager.conf
    section: main
    option: dns
    value: none