#!/bin/bash
set -eo pipefail

version="0.0.1"

cd "./package-src"

echo "Setting permissiong for executables"

chmod +x bin/*/*
chmod +x events/*/*
chmod +x checks/*
chmod +x hooks/*



if [[ -d "./release" ]]; then
  echo "Cleaning release folder"
  rm -rf "./release"
fi

echo "Creating release folder"
mkdir ./release

# prevents fpm complains
find . -name ".DS_Store" -print0 | xargs -0 rm -rf

echo "Building RPM"
fpm -s dir -t rpm -n seaworthy -v "$version" \
  --url "https://github.com/vlipco/seaworthy" \
  --description "Vlipco's Seaworthy minimal cluster components" \
  --vendor "Misc." \
  --epoch "$(date +%s)" \
  --after-install "hooks/after-install" \
  --before-remove "hooks/before-remove" \
  --inputs "inputs_manifest"

echo "Placing RPM in the release folder"
mv *.rpm ../release/

cd ../release

echo "Saving RPM file list to the release folder"
for pkg in $(ls . -1); do
	rpm -qlp $pkg > "${pkg%%.x*}-install-list"
done