#!/bin/bash
set -eo pipefail

date

if [[ $(curl -s --max-time 1 "localhost:4161/ping") == *OK* ]]; then
	echo "Lookupd ping endpoint responded with OK"
else
	echo "Lookupd ping check failed"
	exit 128
fi