- name: Installing extra systemd units
  with_items: extra_units
  copy:
    src: "systemd/{{item}}.service"
    dest: "/etc/systemd/system/{{item}}.service"

- name: Enabling units on boot
  with_items: extra_units
  service: name={{item}}.service enabled=yes

- name: Reloading systemd daemon
  command: /usr/bin/systemctl daemon-reload

- name: Starting units
  with_items: extra_units
  service: name={{item}}.service state=restarted
