- name: Installing docker helper script for systemd units
  copy: "src=bin/{{item}} dest=/usr/local/bin/ mode=0755"
  with_items:
    - docker-rm
    - docker-stop

- include: consul.yml

- set_fact:
    basic_units:
      - nsqd

- name: Installing systemd units
  copy:
    src: "systemd/{{item}}.service"
    dest: "/etc/systemd/system/{{item}}.service"
  with_flattened: 
    - basic_units
    - extra_units | default([])

- name: Enabling units on boot
  service: name={{item}}.service enabled=yes
  with_flattened: 
    - basic_units
    - extra_units | default([])

- name: Reloading systemd daemon
  command: /usr/bin/systemctl daemon-reload

- name: Starting units
  service: name={{item}}.service state=started
  with_flattened: 
    - basic_units
    - extra_units | default([])