- name: Creating consul's config-dir
  file:
    state: directory
    path: "{{consul_conf_tgt_dir}}"

- include: component.yml component=consul
- include: component.yml component=common
- include: component.yml component=nsq
