- include: common.yml

# with_items + include is forbidden, hence the verbosity

- include: _component.yml component=lookupd
  when: install_lookupd

- include: _component.yml component=nsqadmin
  when: install_nsqadmin

- include: _component.yml component=waypoint
  when: install_waypoint

- include: _component.yml component=harbor
  when: install_harbor

- include: _component.yml component=ferry
  when: install_ferry
