- name: Installing misc helper scripts to bin
  copy: "src=bin/ dest=/usr/local/bin/ mode=0755"

- name: Installing misc check scripts to /usr/local/checks
  copy: "src=checks/ dest=/usr/local/checks/ mode=0755"

- include: consul.yml
- include: nsq.yml

- include: extra.yml
  when: extra_units.0 is defined