#!/bin/bash

# to be source by the common provisioner
# when applied to the right machine
# don't run this manually

function three-plus-nodes() {
	nodes=`curl -s "http://127.0.0.1:8500/v1/catalog/nodes" --max-time 1`
	enough_nodes=`echo $nodes | jq '. | length > 2'`
	if [[ "$enough_nodes" == "true" ]]; then
		log "Cluster has at least 3 nodes"
		return 0
	else
		log "Less than 3 nodes in cluster"
		return 1
	fi
}

bootstrap="true"

# perform bootstrap check only if we are running consul already
if [[ "$(systemctl status consul)" == *\(running\)* ]]; then
	log "consul is already running, deciding if bootstrap should be removed"
	if consul-leader && three-plus-nodes; then
		bootstrap="false"
	fi
else
	log "consul has no leader, assuming bootstrap=true"
fi

# Should obtain another nodes IP before changing bootstrap flag

join_cmd='"start_join": ["10.0.77.20"],'

log "Writing consul main config of igniter (bootstrap=$bootstrap)"

cat - > /usr/local/etc/consul/main.json <<ConsulConf
{
	"bootstrap": $bootstrap,
	$(if [[ "$bootstrap" == "false" ]]; then echo $join_cmd; fi)
	"bind_addr": "10.0.77.10",
	"ui_dir": "$consul_ui"
}
ConsulConf
