#!/bin/bash
set -euo pipefail

consul_main_config="/usr/local/etc/consul/main.json"

if [[ `whoami` != "root" ]]; then

  echo "RUN THIS AS ROOT"
  exit 1

fi

function log() {

  echo -e "--> $1"

}

function common_provisioning() {

	seaworthydir=$(echo ~vagrant/seaworthy)
	godir=$(echo ~vagrant/go)

	log "Updating all packages"
	yum update -y &> /dev/null 

	log "Trying to create docker group"
	groupadd docker 2> /dev/null || :

	log "Adding vagrant to the docker group"
	usermod -a -G docker vagrant
	chgrp docker /var/run/docker.sock

	log "Pulling vlipco hull"
	docker pull vlipco/hull &> /dev/null

	cd $seaworthydir 

	log "Bundle installing seaworthy"
	su vagrant -c "bundle install &> /dev/null"

	log "Building all seaworthy images"
	su vagrant -c "rake build:all 2>&1"

	log "Creating consul's configuration dir"
	mkdir -p /usr/local/etc/consul

}

common_provisioning

log "Sourcing host specific provisiner"

my_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$my_dir/$(hostname)"

log "Shell provisioning completed"