#!/bin/bash

# to be source by the common provisioner
# when applied to the right machine
# don't run this manually

log "Writing consul main config of harbor-1"

cat - > /usr/local/etc/consul/main.json <<ConsulConf
{
	"start_join": ["10.0.77.10"],
	"bind_addr": "10.0.77.30"
}
ConsulConf
