#!/bin/bash
set -euo pipefail

if [[ `whoami` != "root" ]]; then
  echo "RUN THIS AS ROOT"
  exit 1
fi

function log() {
  echo -e "--> $1"
}

log "Joining waypoint's consul cluster"
#/usr/local/bin/consul
##/v1/agent/join/10.0.77.10
