#!/bin/bash

# to be source by the common provisioner
# when applied to the right machine
# don't run this manually

consul_ui="/usr/local/src/consul_ui"

if [ ! -d "$consul_ui" ]; then
	log "Downloading web ui for consul"
	cd /usr/local/src
	wget "https://dl.bintray.com/mitchellh/consul/0.2.1_web_ui.zip"
	unzip 0.2.1_web_ui.zip
	mv "dist" "$consul_ui"
fi

function three-plus-nodes() {
	nodes=`curl -s "http://127.0.0.1:8500/v1/catalog/nodes" --max-time 1`
	enough_nodes=`echo $nodes | jq '. | length > 2'`
	if [[ "$enough_nodes" == "true" ]]; then
		log "Cluster has at least 3 nodes"
		return 0
	else
		log "Less than 3 nodes in cluster"
		return 1
	fi
}

bootstrap="true"

# perform bootstrap check only if we are running consul already
if [[ "$(systemctl status consul)" == *\(running\)* ]]; then
	log "consul is already running, deciding if bootstrap should be removed"
	if consul-leader && three-plus-nodes; then
		bootstrap="false"
	fi
else
	log "consul isn't running, assuming bootstrap=true"
fi

# Should obtain another nodes IP before changing bootstrap flag

log "Writing consul main config of igniter (bootstrap=$bootstrap)"

cat - > /usr/local/etc/consul/main.json <<ConsulConf
{
	"bootstrap": $bootstrap,
	"bind_addr": "10.0.77.10",
	"ui_dir": "$consul_ui"
}
ConsulConf
