#!/usr/bin/bash

# Tries to delete a container only if it exists
# the first argument is the container name/id

docker="/usr/bin/docker"

echo "Checking if $1 is running"

if $docker inspect --format='{{.ID}}' "$1" &> /dev/null ; then
  # container exists
  echo "Force removing $1"
  $docker rm -f "$1"
  exit $?
else
  # no such container
  exit 0
fi
