#!/bin/bash

if [[ "$1" == "short" ]]; then
	exlusions="(vboxadd|systemd-|fedora)"
else
	exlusions="(---)"
fi

function unit-list() {
	systemctl -t service --full --all list-units \
	| awk '{print $1 }' 2>/dev/null \
	| grep -E '.*\..*' | grep -E -v "$exlusions"
}

for service in $(unit-list); do
    if systemctl is-enabled $service &> /dev/null; then
        echo "$service"
    fi
done 2>/dev/null
