#!/bin/bash

# nsqevent ping is triggered with a random string
# we then check the tail of $tail_file includes it

date

expected_random=`date +%s.%N | sha256sum | base64 | head -c 32 ; echo`

echo "Sending random: $expected_random"

echo "Truncating the ping_events file to prevent growth"

tail_file="/tmp/ping_events"
lc=`wc -l $tail_file | awk '{print $1}'`
last_line="$(( $lc - 20 ))"
sed -i "1,$last_line d" $tail_file

echo "Sending ping event to a random nsqd instance"

nsqd_http="nsqd.service.consul:4151"

trigger_result=`nsq_trigger --nsqd-http-address $nsqd_http \
  --topic events ping "$(hostname): $expected_random"`

function ping_received() {
	tail -n 20 $tail_file | grep -G "$expected_random" &> /dev/null
	return $?
}

if echo $trigger_result | grep -G "$nsqd_http: OK" &> /dev/null; then

	# 8 retries, sleeps 250ms between waits
	retries=1

	until ping_received || [ $retries -eq 5 ]; do
	   echo "Retry #$(( retries++ ))"
	   sleep 0.25
	done

	if [ $retries -eq 5 ]; then
		echo "Tried for 2 seconds but the the ping event wasn't detected:"
		echo "the payload wasn't present in the tail of $tail_file"
		echo "Closing with a warning"
		exit 1
	else
		echo "Local nsqevent service OK"
		echo "ping event was processed within $(( 250 * $retries ))ms"
		exit 0	
	fi
else
	echo "Failed to trigger the event"
	echo "Trigger command result was: $trigger_result"
	echo "Closing with a warning"
	exit 1
fi