#-----------------------------------------#
# consul json templates for configuration #
#-----------------------------------------#

- name: Ensuring consul templates directory exists
  file:
    state: directory
    path: "{{component_tgt_dir}}/consul"

- name: Compiling consul templates
  with_fileglob: consul_templates_glob
  template:
    src: "{{item}}"
    dest: "{{component_tgt_dir}}/consul/"

- include: "_folder_items.yml src={{consul_conf_src_dir}} link_to={{consul_conf_tgt_dir}}/consul"