#-------------------------------------#
# executables to be added to the path #
#-------------------------------------#

- name: Copying component's folder
  copy:
    src: "{{name}}"
    dest: "{{consul_components_tgt_dir}}"

- include: "_folder_items.yml src={{bin_src_dir}} mode=0755 link_to=/usr/local/bin"

- include: "_folder_items.yml src={{checks_src_dir}} mode=0755"