#-------------------------------#
# systemd units enabled on boot #
#-------------------------------#

- stat: "path={{units_src_dir}}"
  register: units_st

- name: Listing systemd units to enable
  when: units_st.stat.isdir is defined
  command: "ls {{units_src_dir}} -1"
  register: units_list

- name: Enabling systemd units on boot
  when: units_list is defined
  command: "systemctl enable {{units_src_dir}}/{{item}}"
  notify: "restart {{name}}"
  with_items: units_list.stdout_lines