#!/bin/bash
parent=$$
echo "PID is $parent"
sem="sem --gnu --ungroup"

trap 'kill 0' SIGINT

$sem --jobs 2 --id my_id './stamp A UP; sleep 2; ./stamp A' 


$sem --jobs 2 --id my_id './stamp B UP; sleep infinity; ./stamp B' 

./stamp ---
fatal_cmd="./stamp C-$parent; kill -SIGINT $parent"
$sem --fg --jobs 2 --id my_id $fatal_cmd 
./stamp POSTC


$sem --wait --id my_id
./stamp ALL