- name: Listing regular files to affect
  register: folder_list
  ignore_errors: True
  command: find . -maxdepth 1 -type f chdir={{src}}

- name: Changing files' mode
  when: mode is defined and folder_list|success
  with_items: folder_list.stdout_lines
  file:
    path: "{{src}}/{{item}}"
    mode: "{{mode}}"

- name: Linking files in target folder
  when: folder_list | success
  when: link_to is defined
  with_items: folder_list.stdout_lines
  file:
    force: yes
    state: link
    src: "{{src}}/{{item}}"
    dest: "{{link_to}}/{{item}}"