- name: Creating misc. directories
  file: "state=directory path={{item}}"
  with_items: ansible_dirs

- include: >
    _cond_get.yml pkg="consul"
    version_command="/usr/local/bin/consul --version" 
    expected_version="{{consul_version}}" 

- include: >
    _cond_get.yml pkg="nsq"
    version_command="/usr/local/bin/nsqd --version" 
    expected_version="{{nsq_version}}" 

- include: _component.yml name=consul tags=consul
  
- include: _component.yml name=common tags=common

- include: _component.yml name=nsq tags=nsq

# with_items + include is forbidden, hence the verbosity

- include: _component.yml name=lookupd
  when: install_lookupd

- include: _component.yml name=nsqadmin
  when: install_nsqadmin

- include: _component.yml name=waypoint
  when: install_waypoint

- include: _component.yml name=harbor
  when: install_harbor

- include: _component.yml name=ferry
  when: install_ferry
