#!/bin/bash
set -eo pipefail

function log() {
  echo " ---> $1"
}

cd "/usr/local/src"

log "Installing nsq"
tar xf nsq-0.2.28.tar.gz
mv "nsq-0.2.28-linux-amd64.go1.2.1/bin/*" "/usr/local/bin/"
rm -rf "nsq-0.2.28-linux-amd64.go1.2.1"

log "Installing Consul"
unzip consul-0.2.0.zip
mv consul /usr/local/bin/
