#!/bin/bash
set -euo pipefail

echo "Starting works $$"

#for NUM in `seq 1 64`; do
#	#trap "echo !!$NUM && exit 0" $NUM
#	trap "echo !!$NUM $0; exit 0" $NUM
#done

echo "Working for infinity"
exec sleep infinity


