#!/bin/bash
set -eo pipefail

echo
echo "Performing Seaworthy after-install tasks:"
echo

if [[ ! -e "/etc/resolv.conf.orig" ]]; then
	echo "Saving copy of current resolv.conf to /etc/resolv.conf.orig"
	cat /etc/resolv.conf > /etc/resolv.conf.orig
fi

echo "Creating local configuration directories/files"

mkdir -p /usr/local/lib/seaworthy/components
mkdir -p /etc/cluster/consul
mkdir -p /etc/cluster/checks
mkdir -p /etc/cluster/units
mkdir -p /etc/cluster/components

common_components=(utils consul nsq)
for component in "${common_components[@]}"; do
	swrth components enable "$component"
	echo
done

echo "Done."

exit 0