#!/bin/bash

# nsqd http endpoint is checked for ok

date

if [[ $(curl -s --max-time 1 "localhost:4151/ping") == *OK* ]]; then
	echo "Nsqd ping endpoint responded with OK"
else
	echo "Nsqd ping check failed"
	exit 128
fi

# Check with all known lookupds in the cluster
# and if at least one of them doesn't know about
# this node, then trigger a restart of the local nsqd

function json_includes_hostname() {
	length=`cat - | jq ".|map( select( .|contains(\"$(hostname)\") ) ) | length"`
	if [[ "$length" != "0" ]]; then
		return 0
	else
		return 1
	fi
}

if consul-leader &> /dev/null; then
	# array with nodes
	url="127.0.0.1:8500/v1/catalog/service/lookupd"
	endpoints=$(curl -s --max-time 1 $url | jq -r '.[].Address')

	total_count=$(echo $endpoints | wc -l)
	
	restart_nsqd=false

	echo "Checking local nsqd annoucement with $total_count lookupd:"
	for host in $endpoints; do
		
		if lookupd-producers $host | json_includes_hostname; then
			echo "  - $host lookupd knows about $(hostname)"
		else
			echo "  - !! $host doesn't know about $(hostname)"
			restart_nsqd=true
		fi
	done
	if [[ "$restart_nsqd" == "false" ]] ; then
		echo "OK. Every lookupd in the cluster knows about this host"
		exit 0
	else
		echo -n "Triggering nsqd restart"
		systemctl restart nsqd && echo '...restart sent'
		echo "Marking check with warning"
		exit 1
	fi
else
	echo "no cluster leader"
	exit 128
fi