#!/bin/bash
set -eo pipefail

version="0.0.1"

function make_bin () {
	if [[ -d "$1" ]]; then
		find "$1" ! -type d -exec chmod +x {} \;
	fi
}

echo "Setting permissions for core executables"

make_bin "core/bin"
chmod +x "core/lib/cli/swrth"

echo "Setting permissions for components executables"

for component in $(ls components -1); do
	make_bin "$component/bin"
	make_bin "$component/events"
	make_bin "$component/checks"
	make_bin "$component/hooks"
done

# prevents fpm complains if host machine is osx
find . -name ".DS_Store" -print0 | xargs -0 rm -rf

echo "Building RPM"
fpm -s dir -t rpm -n seaworthy -v "$version" --rpm-os "linux" \
  --vendor "Misc." --epoch "$(date +%s)" --iteration "alpha" \
  --maintainer "David Peláez <david@vlipco.co>" \
  --url "https://github.com/vlipco/seaworthy" \
  --description "vlipco's minimal cluster toolkit" \
  --after-install "core/lib/hooks/after-install" \
  --before-remove "core/lib/hooks/before-remove" \
  --directories "/usr/lib/seaworthy" \
  --config-files "/etc/cluster/default.conf" \
  --inputs "inputs_manifest"
