#!/bin/bash
set -eo pipefail

version="0.0.1"

function make_bin () {
	if [[ -d "$1" ]]; then
		find "$1" ! -type d -exec chmod +x {} \;
	fi
}

echo "Setting permissions for core executables"

make_bin "bin"
chmod +x "seaworthy/clitool/swrth"

echo "Setting permissions for components executables"

components_dir="seaworthy/components"
for component in $(ls $components_dir -1); do
	make_bin "$components_dir/$component/bin"
	make_bin "$components_dir/$component/events"
	make_bin "$components_dir/$component/checks"
	make_bin "$components_dir/$component/hooks"
done

# prevents fpm complains if host machine is osx
find . -name ".DS_Store" -print0 | xargs -0 rm -rf

echo "Building RPM"
fpm -s dir -t rpm -n seaworthy -v "$version" --rpm-os "linux" \
  --vendor "Misc." --epoch "$(date +%s)" --iteration "alpha" \
  --maintainer "David Peláez <david@vlipco.co>" \
  --url "https://github.com/vlipco/seaworthy" \
  --description "vlipco's minimal cluster toolkit" \
  --after-install "hooks/after-install" \
  --directories "/usr/lib/seaworthy" \
  --inputs "inputs_manifest"
