# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure VAGRANTFILE_API_VERSION do |config|

  config.vm.box = 'digital_ocean'
  config.vm.synced_folder ".", "/vagrant", disabled: true


  config.vm.provider :digital_ocean do |provider, override|
    override.ssh.private_key_path = ENV['DO_SSH_KEY']
    provider.image = "Fedora 20 x64"
    provider.client_id = ENV['DO_CLIENT_ID']
    provider.api_key = ENV['DO_API_KEY']
    provider.size = "1GB"
    provider.setup = false
    provider.private_networking = true
  end

  config.vm.define "igniter" do |igniter|
    igniter.vm.provider :digital_ocean do |igniter_provider, igniter_override|
      igniter_provider.size = "512MB"
    end
  end

  config.vm.define "waypoint" do |waypoint|
    waypoint.vm.hostname = "waypoint"
  end

  config.vm.define "external-harbor" do |external_harbor|
    external_harbor.vm.hostname = "external-harbor"
  end

  config.vm.define "ferry" do |ferry|
    ferry.vm.hostname = "ferry"
  end

end
