- name: "consul: Checking current consul version"
  shell: consul --version || echo null
  # this requires in ansible.cfg executable=/usr/bin/bash -l
  register: consul_version_found
  changed_when: False

- name: "consul: Choosing random string for download folder"
  when: "'{{consul_version}}' not in consul_version_found.stdout"
  shell: date +%s.%N | sha256sum | base64 | head -c 32 ; echo
  register: random_dirname

- name: "consul: Setting misc. variables for installation"
  when: random_dirname|changed
  set_fact:
    consul_tmp_dir: "/tmp/consul.{{random_dirname.stdout}}"
    link_folder_script: "../../files/generic_install/link-folder"

- name: "consul: Creating temporary download folder"
  when: consul_tmp_dir is defined
  file: "path={{consul_tmp_dir}} state=directory"

- name: "consul: Downloading consul"
  when: consul_tmp_dir is defined
  register: consul_download
  get_url:
    sha256sum: "{{consul_sha256sum}}"
    url: "https://dl.bintray.com/mitchellh/consul/{{consul_pkg_name}}.zip"
    dest: "{{consul_tmp_dir}}/{{consul_pkg_name}}.zip"

- name: "consul: Extracting consul binaries"
  when: consul_download|changed
  shell: "cd {{consul_tmp_dir}} && unzip {{consul_pkg_name}}.zip"

- name: "consul: Removing previous version if present"
  when: consul_download|changed
  file: path=/cluster/vendor/consul state=absent

- name: "consul: Creating destination directory"
  when: consul_download|changed
  file: path=/cluster/vendor/consul state=directory

- name: "consul: Installing consul binaries"
  when: consul_download|changed
  shell: "cd {{consul_tmp_dir}} && mv consul /cluster/vendor/consul"

- name: "consul: Downloading consul UI"
  when: consul_download|changed
  get_url:
    sha256sum: "{{consul_ui_sha256sum}}"
    url: "https://dl.bintray.com/mitchellh/consul/{{consul_ui_pkg_name}}.zip"
    dest: "{{consul_tmp_dir}}/{{consul_ui_pkg_name}}.zip"

- name: "consul: Extracting consul UI"
  when: consul_download|changed
  shell: "cd {{consul_tmp_dir}} && unzip {{consul_ui_pkg_name}}.zip"

- name: "consul: Installing consul UI"
  when: consul_download|changed
  shell: "cd {{consul_tmp_dir}} && mv dist /cluster/vendor/consul/ui"

- name: "consul: Linking binaries to local path"
  script: "{{link_folder_script}} /cluster/vendor/consul /usr/local/bin"
  when: consul_download|changed

- name: "consul: Checking installed version"
  when: consul_download|changed
  shell: consul --version
  register: recent_version 

- when: consul_download|changed
  assert:
    that: "'{{consul_version}}' in recent_version.stdout"

- name: "consul: Deleting temporary download folder"
  when: consul_tmp_dir is defined
  file: "path={{consul_tmp_dir}} state=absent"