- name: "waypoint: Installing custom sshd_config"
  shell: >
    conf_src=/cluster/components/waypoint/misc/sshd_config && 
    [ -e "$conf_src" ] && 
    cat $conf_src > /etc/ssh/sshd_config

- name: "waypoint: Reloading sshd to support git pushes"
  shell: >
    /usr/sbin/sshd -t && 
    /bin/kill -HUP $(systemctl status sshd | grep PID | awk '{print $3}')

- name: "waypoint: Initializing git user"
  shell: /usr/local/bin/gitreceive init

- name: "waypoint: Creating slugs folder"
  file: 
    path: /var/local/git/slugs 
    state: directory
    owner: git
