#!/bin/bash
set -eo pipefail

date

echo "Checking systemctl for failed units"

# don't use pipefail in this command
failed_count="$(systemctl -t service --failed | grep failed | grep -v 'masked' | wc -l || :)"

if [[ $failed_count == "0" ]]; then
	echo "No units are failing. Everything OK."
	exit 0
else
	echo "Some units are currently in a failed state:"
	systemctl -t service --failed | grep failed | awk '{print "  - "$1 }' 2>/dev/null
	exit 1
fi
