#!/usr/bin/bash
set -eo pipefail

component="$1"

if [[ -z "$2" ]]; then
  unit="$1.service"
else
  unit="$2"
fi

echo "Enabling $unit from $component component"
systemctl enable "/cluster/components/$component/systemd/$unit"

echo "Restarting $unit"
systemctl restart "$unit"
