#!/bin/bash
set -eo pipefail

src="$1"
dest="$2"
if [[ -d "$src" ]]; then
	cd "$src"
	echo "Linking items in $src:"
	for file in $(ls . -1); do
		rm $dest/$file &> /dev/null || true
		echo "  $file -> $dest/$file"
		ln -s $src/$file $dest/$file
	done
else
	echo "$src doesn't exist, skipping"
fi