#!/usr/bin/env fish

source (dirname (status --current-filename))/autoctono/atn.fish

atn.task.add "consul" "Consul cluster operations"
#atn.task.add components 	"Manage local cluster components"
#atn.task.add waypoint 	"Waypoint component operations"

function main -a task
	if test $task
		atn.set_rargs $argv
		atn.task.run $task $rargs
	else
		echo "No task was given"
	end
end

main $argv
