---

- name: prune links
  notify: reload systemd daemon
  script: "generic_install/prune-links"

- name: reload systemd daemon
  command: systemctl daemon-reload

- name: restart geard
  service: 
    name: geard.service 
    state: restarted
    enabled: yes

- name: restart consul
  notify: 
    - consul join
    - wait for leader
  service: 
    name: consul.service 
    state: restarted
    enabled: yes

- name: consul join
  notify: wait for leader
  when: consul_start_join is defined
  command: "consul join {{consul_start_join}}"

- name: wait for leader
  notify: systemd healthcheck
  shell: /usr/local/bin/consul-leader
  register: leade_result
  until: not (leade_result.stdout | search('null'))
  retries: 12
  delay: 5

- name: restart lookupd
  service: 
    name: lookupd.service 
    state: restarted
    enabled: yes

- name: restart nsq
  service: 
    name: "{{item}}.service"
    state: restarted
    enabled: yes
  with_items:
    - nsqd
    - nsqevents

- name: restart nsqadmin
  service: 
    name: nsqadmin.service 
    state: restarted
    enabled: yes

- name: restart waypoint
  service: 
    name: waypoint.service 
    state: restarted
    enabled: yes

- name: restart harbor
  service: 
    name: harbor.service 
    state: restarted
    enabled: yes

- name: restart ferry
  service: 
    name: ferry.service 
    state: restarted
    enabled: yes

- name: systemd healthcheck
  shell: "sleep 5 && systemctl --failed"
  register: healthcheck_result
  until: healthcheck_result.stdout | search('0 loaded units listed')
  retries: 10
  delay: 2