- name: Defining GOPATH for compilation
  set_fact:
    gopath: /usr/local/src/go
    geard: /usr/local/src/go/src/github.com/openshift/geard

- name: Getting geard repository
  git:
    repo: https://github.com/openshift/geard.git
    version: 178db29f02b5d660b370956c920dd1d13484ede3
    depth: 1
    dest: "{{geard}}"

- name: Compiling geard with SELinux and systemd unit
  shell: "export GOPATH={{gopath}} && cd {{geard}} && contrib/build -s -g"


