---

- hosts: all
  handlers:
    - include: components/handlers.yml
  tasks:
    - include: generic/install.yml component=consul
    - include: generic/install.yml component=common
    - include: generic/install.yml component=nsq

    - include: generic/install.yml component=nsqadmin
      when: install_nsqadmin | default(False)
