---

- hosts: all
  handlers:
    - include: components/handlers.yml
  tasks:

    - include: vagrant/development.yml
      when: vagrant_development | default(False)


    - include: geard.yml tags=geard
    - name: Save DNS backup
      shell: >
        cp /etc/resolv.conf /etc/resolv.conf.orig
        creates=/etc/resolv.conf.orig

    - name: Disable NetworkManager DNS management
      ini_file:
        backup: yes
        dest: /etc/NetworkManager/NetworkManager.conf
        section: main
        option: dns
        value: none

    - name: Removing previous cluster configuation
      with_items:
        #- /cluster/data
        - /cluster/etc
      file:
        path: "{{item}}"
        state: absent

    - include: generic/install.yml component=consul

    - include: generic/install.yml component=common tags=common
    - include: generic/install.yml component=nsq

    - include: generic/install.yml component=nsqadmin
      when: install_nsqadmin | default(False)

    - include: generic/install.yml component=lookupd
      when: install_lookupd | default(False)

    - include: generic/install.yml component=harbor
      when: install_harbor | default(False)

    - include: generic/install.yml component=waypoint
      when: install_waypoint | default(False)
