---

- hosts: all
  handlers:
    - include: components/handlers.yml
  tasks:
    - include: vagrant/development.yml
      when: vagrant_development | default(False)

    - include: generic/install.yml component=nsqadmin
      when: install_nsqadmin | default(False)

    - include: generic/install.yml component=lookupd
      when: install_lookupd | default(False)

    - include: generic/install.yml component=harbor
      when: install_harbor | default(False)

    - include: generic/install.yml component=waypoint
      when: install_waypoint | default(False)
