#!/usr/bin/env bash
set -eo pipefail

SCRIPT_PATH="$(dirname $0)"
source "$SCRIPT_PATH/bangsh/bang.sh"

b.set bang.working_dir "$PWD"

cd "$SCRIPT_PATH" > /dev/null

b.module.require task

function _unkown_task() {
	echo "Unknown command '$task'"
}

b.task.add components "Manage local cluster components"
b.task.add units "Components systemd units commands"
#b.task.add info "Information retrieving commands"
b.task.add consul "Consul component operations"

task="$1"; shift

if [[ -n "$task" ]]; then
	b.try.do b.task.run $task $@
	b.catch TaskNotKnown _unkown_task
	b.finally exit
	b.try.end
else
	# todo show the usage
	echo "---"
fi

exit 0