#!/usr/bin/env bash

# Note that this options will force you to b.finally
# in all exceptions handling
# TODO: report that bug
set -eo pipefail


SCRIPT_PATH="$(dirname $0)"
source "$SCRIPT_PATH/bangsh/bang.sh"

b.set bang.working_dir "$PWD"

cd "$SCRIPT_PATH" > /dev/null

#b.module.require task

function _unkown_task() {
	echo "Unknown command '$task'"
}

b.module.require task2

# registers tasks/components as a group of task under components
# namespace. e.g swrth components list -> tasks/components/list.sh

# groups are handled transparently!
b.task.add components "Manage local cluster components"

#b.task.add units "Components systemd units commands"
#b.task.add info "Information retrieving commands"
b.task.add consul "Consul component operations"

task="$1"; shift

if [[ -n "$task" ]]; then
	b.try.do b.task.run $task $@
	b.catch TaskNotKnown _unkown_task
	b.finally exit
	b.try.end
else
	# todo show the usage
	echo "---"
fi

exit 0