#!/usr/bin/env bash
set -eo pipefail

SCRIPT_PATH="$(dirname $0)"
source "$SCRIPT_PATH/bangsh/bang.sh"

b.set bang.working_dir "$PWD"

cd "$SCRIPT_PATH" > /dev/null

b.module.require task

function _unkown_task() {
	echo "No such command, try swrth help"
}

b.task.add components "Manage local cluster components"

task="$1"
shift

if [ -n "$task" ]; then
	b.try.do b.task.run $task "$@"
	b.catch TaskNotFound _unkown_task
	b.try.end
else
	# todo show the usage
	echo "---"
fi