#!/bin/bash
set -eo pipefail

events_folder="$(dirname $0)"

role=$(echo $@ | jq -r '.role')
app=$(echo $@ | jq -r '.app')
revision=$(echo $@ | jq -r '.revision')

if cat /cluster/etc/harbor_role | grep -G "$role" &> /dev/null; then
	consulkv $(hostname)/log/receive "$(date) $@ -- $role $app $revision"
	source_url="waypoint.service.consul/$role/$app/$revision.tar"

	cd $(mktemp -d /tmp/$app.XXXX)

	echo "Downloading $source_url in $(pwd)"
	curl -s "$source_url" | tar x

	echo "Pulling latest version of vlipco/sti-ruby"
	docker pull vlipco/sti-ruby

	echo "Building sti image"
	# todo add --rm after update
	sti build . vlipco/sti-ruby "$app"

	echo "Balancing node ($events_folder/balance)"
	$events_folder/balance "$role" "$app"
else
	echo "Skipping event because of role mismatch"
fi