#!/bin/bash
set -eo pipefail

if [ -t 0 ]; then
  # No payload sent over stdin
  serf event error "type=deploy,msg=Deploy event needed a payload"
  exit 1
else
  payload=`cat -`
fi

# Inits the deployment of an app
# It installs the app if needed
# starts or restarts according to the case

app="$1"

echo "Triggering gear actions for $app"

gear install vlipco/ship "$app" -p 5000:0
gear set-env "$app" APP_NAME="$app" SLUG_SERVER=172.17.42.1:5100
gear start "$app"
