#!/bin/bash

exec /opt/bin/docker run --tty=false -i --rm \
	-p $SERF_PORT:$SERF_PORT -p $SERF_PORT:$SERF_PORT/udp \
	-e SERF_BIND_PORT=$SERF_PORT \
	-e SERF_ROUTABLE_IP=$SERF_ROUTABLE_IP \
	-e SERF_ROLE=admiral \
	-e SERF_NODE_NAME=admiral \
	vlipco/deckhouse "/usr/local/bin/start-serf"