# --------------
#  Preparations
# --------------

- name: Set the hostname
  copy: "content={{inventory_hostname}} dest=/etc/hostname"

- name: Mask firewalld
  shell: systemctl mask firewalld

- name: Stop firewalld
  command: systemctl stop firewalld

- name: Disable rngd (if present)
  shell: systemctl disable rngd.service

- name: Set SELINUX to permissive
  lineinfile: dest=/etc/selinux/config regexp=^SELINUX= line=SELINUX=permissive

- name: Flush iptables
  command: iptables --flush

- name: Removing previous vendor folder
  when: clean_vendor_install | default(False)
  file: path=/cluster/vendor state=absent

- name: Removing previous components folder
  when: clean_components_install | default(True)
  file: path=/cluster/components state=absent

- name: "Pruning broken links (paths, cluster and systemd folders)"
  script: generic_install/prune-links

# --------
#  Common
# --------

- include: generic_install.yml component=common tags=common
- include: installers/common.yml tags=common

- include: installers/consul.yml tags=consul
- include: generic_install.yml component=consul tags=consul

- include: installers/geard.yml tags=geard
- include: generic_install.yml component=geard tags=geard

- include: installers/nsq.yml tags=nsq
- include: generic_install.yml component=nsq tags=nsq

# ---------
#  Lookupd 
# ---------

- include: generic_install.yml component=lookupd
  when: install_lookupd | default(False)

# ----------
#  Waypoint 
# ----------

- include: generic_install.yml component=waypoint tags=waypoint
  when: install_waypoint | default(False)

- include: installers/waypoint.yml tags=waypoint
  when: install_waypoint | default(False)

# ----------
#  NSQadmin 
# ----------

- include: generic_install.yml component=nsqadmin tags=nsqadmin
  when: install_nsqadmin | default(False)

# --------
#  Harbor
# --------

- name: Saving Harbor role
  copy: "content={{harbor_role}} dest=/cluster/etc/harbor_role"
  when: install_harbor | default(False)

- include: generic_install.yml component=harbor tags=harbor
  when: install_harbor | default(False)
#
#- include: generic_install.yml component=ferry
#  when: install_ferry | default(False)